### ISSUE TITLE
Install on CentOS 7

### ISSUE THREAD

**Issue by rbicelli** [ercpe/amavisvt#8]
Hello! Could provide a guide for install and run amavisvt on CentOS 7? I cannot get It to work.
Thanks

**Comment by zimico** [comment]
Hello, I already tried it on centos7 but unfortunately it doesn't work. The error:
```
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: 2019-11-11 21:41:33,221 ERROR   [Thread-2] Error asking virustotal about files
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: Traceback (most recent call last):
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: (self._dns_host, self.port), self.timeout, **extra_kw
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: raise err
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: sock.connect(sa)
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: socket.timeout: timed out
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: During handling of the above exception, another exception occurred:
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: Traceback (most recent call last):
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: chunked=chunked,
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: self._validate_conn(conn)
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: conn.connect()
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 334, in connect
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: conn = self._new_conn()
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 164, in _new_conn
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: % (self.host, self.timeout),
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3ffc1c6278>, 'Connection to www.virustotal.com timed out. (connect timeout=10.0)')
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: During handling of the above exception, another exception occurred:
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: Traceback (most recent call last):
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: timeout=timeout
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
Nov 11 21:41:33 mail.zimilab.com amavisvtd[4273]: raise MaxRetryError(_pool, url, error or ResponseError(cause))
```
I can manually carry out the request successfully: 
```
[root@mail ~]# curl -X POST https://www.virustotal.com/vtapi/v2/file/scan -F apikey=efe-------------------my key------------35 -F file=/root/myfile.sh
{"scan_id": "44e370512eadbcf17fdb925ac32157dc914be18c4d3c5caa3f606f575c9d3002-1573630626", "sha1": "c652a738c179fa72cc075ba27821ef4c5a62085e", "resource": "44e370512eadbcf17fdb925ac32157dc914be18c4d3c5caa3f606f575c9d3002", "response_code": 1, "sha256": "44e370512eadbcf17fdb925ac32157dc914be18c4d3c5caa3f606f575c9d3002", "permalink": "https://www.virustotal.com/file/44e370512eadbcf17fdb925ac32157dc914be18c4d3c5caa3f606f575c9d3002/analysis/1573630626/", "md5": "6f7e1dd90c4d6d6970cfbfb1adb3409f", "verbose_msg": "Scan request successfully queued, come back later for the report"}
```
My Centos 7 comes with Python 3.6.

**Comment by ercpe** [comment]
Please make sure that the process can access virustotal.com - e.g. check your network connection, proxy configuration (if applicable), etc.

**Comment by zimico** [comment]
Dear,
Thank for your support. You are right! After disable firewall (with some advance rules which block outbound connection), now I can connect to virustotal. I will test and update if it works ok or not.

**Comment by zimico** [comment]
Dear Johann Schmitz,
Our zimbra mail server now works with virustotal. However, I am not sure about how many request amavisvtd use. I test with single email: some times it takes 3 requests and some time it takes 2 requests. For example, when I use http://www.aleph-tec.com/eicar/index.php to send 4 virus test mails to our system, amavisvtd log shows that API-Limit exceeded! However when I use gmail to send 4 test mails to our system (without any attachment), there is quota warning, and them number of requests increase by 12 requests. Could you please explain about those?
Another thing to note is I have to manually remove amavisvtd.sock file before restarting the service.
Many thanks,
Minh.
